import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black text-white`}
      >
        <div className="container mx-auto px-4 xl:px-0">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
